import { poppins } from '@/app/fonts';
import './globals.css';

export const metadata = {
  title: 'Legal Solutions',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="max-w-screen-xl mx-auto">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
